# Generated by Django 5.1.2 on 2025-03-04 15:04

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_flower_description_alter_flower_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flower',
            name='image',
            field=cloudinary.models.CloudinaryField(default='your_default_image_url', max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='flower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='shop.flower'),
        ),
    ]
