# Generated by Django 5.1.2 on 2025-03-04 15:34

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_flower_image_alter_orderitem_flower'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flower',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
